### ISSUE TITLE
להוסיף אוטומציה של מירג׳וג׳

### ISSUE THREAD

**Issue by UrielOfir** [UrielOfir/os-practice#120]

**Comment by gurelbs** [comment]
lets do it!

**Comment by UrielOfir** [comment]
כשזה עובד צריך לעדכן גם את הרידמי שמדריך איך לעשות פול-ריקווסט שידריך להוסיף קובץ בהתאם לדרישות של הולידציה, כדי שהפול-ריקווסט יאושר אוטומטית.

**Comment by UrielOfir** [comment]
@ronnahmias Shoule I assign you?

**Comment by ronnahmias** [comment]
Yes!

Can you set conditions when to merge the PR?
We also want to close the issue. so we need to add ref from the PR to the issue

**Comment by UrielOfir** [comment]
צריך לבדוק שאנשים הוסיפו קובץ אחד של md במקום הנכון וזהו בגדול.

**Comment by EyalBrilling** [comment]
לשם התיעוד.
על בסיס #398
לוקאלית הautomerge עובד אך עדיין לא עובד בפרויקט.
בתוך הworkflow מגדירים הרשאה שנותנת לסביבת העבודה לכתוב לתוך הפרויקט:
`    permissions:
      contents: write
`
 ניתן לראות בgithub action שאכן לוקאלית ההרשאה לכתיבה נשארת(ומרגוג עובד) אך בפרויקט הזה ההרשאה חוזרת לread only ומתקבלת שגיאה כאשר הworkflow מנסה למרג'ג:
`
Failed to merge PR: Resource not accessible by integration
`
הפתרון הוא כנראה להשתמש בPAT - אנסה זאת בהמשך השבוע.
האינטרנט גם אומר שניתן לתת הרשאות לactions בsettings של הפרויקט אך נראה לי שרק ל @UrielOfir יש גישה לכך. [ככתוב כאן](https://stackoverflow.com/a/76869762/10610303)

**Comment by UrielOfir** [comment]
עדכנתי את ההגדרות:
![Screenshot from 2024-05-06 19-52-59](https://github.com/UrielOfir/os-practice/assets/30144878/ada7eedb-8845-4fcf-b80b-971d8ea223b0)

**Comment by EyalBrilling** [comment]
תודה @UrielOfir 
![image](https://github.com/UrielOfir/os-practice/assets/43183029/36200664-aaa5-4dd1-96df-9a96aeb7aae5)

מאוד מוזר שעדיין מחזיר read ,אולי זה עניין של cache של ההגדרות. אנסה מחר עם pr חדש.

**Comment by UrielOfir** [comment]
זה נראה שזה עובד.
אני סוגר את האישיו הזה :)
