### ISSUE TITLE
First MD file

### ISSUE THREAD

**Issue by itamarKraitman** [UrielOfir/os-practice#300]
### Explain what you want do to (i.e. create an MD file)

Create my first MD file

**Comment by DavidHaver** [comment]
ברוך הבא איתמר
בהצלחה בהמשך הפעילות בעולם הקוד הפתוח :)

**Comment by UrielOfir** [comment]
תודה דוד על הטיפול בפול-ריקווסטים :)

אם תוכל להרים אוטומציה זה יהיה הכי טוב.
אתה בכיוון? או שבינתיים זה לא מטריד אותך יותר מדי לאשר ידנית.

**Comment by DavidHaver** [comment]
> תודה דוד על הטיפול בפול-ריקווסטים :)
> 
> אם תוכל להרים אוטומציה זה יהיה הכי טוב. אתה בכיוון? או שבינתיים זה לא מטריד אותך יותר מדי לאשר ידנית.


חשבתי שירדנו מהקטע של מארג' אוטומטי בגלל בעיות אבטחה (אנשים יכולים לשתול קוד זדוני\תכנים לא ראויים\פולטיים אם אין בכלל פיקוח)
בכל מקרה לי לא יצא להתעסק עם אוטומציות לגיטהאב נראה לי אלישע אמר שהוא יכול לעשות את זה (אני יכול גם לנסות פשוט לא כל כך זמין לזה כרגע)
בנתיים אין לי בעיה לאשר ידנית זה לוקח בדיוק דקה ואפשר לעשות את זה מהאפלקציה בטלפון

**Comment by UrielOfir** [comment]
האפשרות לחסוך את העבודה הידנית שווה את המחיר של בעיית אבטחה קלושה.

בכל אופן אם אתה מסתדר עם האישור הידני זה מעולה :)

**Comment by DavidHaver** [comment]
כשיהיה לי זמן נראה מה זה דורש לעשות את זה אוטומטי
אני לא כול כך מכיר את המנגנונים של גיטהאב
