### ISSUE TITLE
Add MD title -tutorial

### ISSUE THREAD

**Issue by shmuel-fisher** [UrielOfir/os-practice#346]
### Explain what you want do to (i.e. create an MD file)

create an MD file

**Comment by DavidHaver** [comment]
ברוך הבא שמואל
בהצלחה בהמשך הפעילות בעולם הקוד הפתוח :)

**Comment by shmuel-fisher** [comment]
תודה רבה

‫בתאריך יום ג׳, 12 במרץ 2024 ב-21:49 מאת ‪DavidHaver‬‏ <‪
***@***.***‬‏>:‬
