### ISSUE TITLE
Add MD file

### ISSUE THREAD

**Issue by GityFilip** [UrielOfir/os-practice#347]
### Explain what you want do to (i.e. create an MD file)

create a new MD file

**Comment by GityFilip** [comment]
אשמח אם תוכלו לעזור לי
אני מנסה כבר כמה ימים לקחת אישו ולעבוד עליו, אבל אני לא יודעת מאיפה ועם מה
להתחיל.
יש איזה סימון שמרמז על אישו שמתאים למתחילים?

יש לי נסיון של לפני כעשר שנים בC# וג'אווהסקריפט
ועכשיו רוצה מאוד לחזור לתחום אבל צריכה קצת הכוונה כדי לחזור לענינים.

אשמח מאוד לתשובה
תודה!

‫בתאריך יום ג׳, 12 במרץ 2024 ב-18:36 מאת ‪DavidHaver‬‏ <‪
***@***.***‬‏>:‬

**Comment by DavidHaver** [comment]
בשמחה
את נמצאת בווטסאפ ובדיסקורד של הקהילה?
נראה לי יהיה יותר נוח לדבר שם
יש פרויקט מסויים שאת רוצה לתרום לו?

**Comment by GityFilip** [comment]
יש לי מכשיר כשר בלי וואטסאפ
הדיסקורד חסום לי כרגע , ביקשתי פתיחה.

עברתי על הפרויקטים שאתם מציעים פה-
https://maakaf.netlify.app/en/members/en_projects_list/
כבר עשיתי פורק לפרויקט הזה- https://github.com/cboard-org/cboard
אבל התקשיתי להבין מה יכול להתאים לידע שלי...


‫בתאריך יום ב׳, 1 באפר׳ 2024 ב-11:55 מאת ‪DavidHaver‬‏ <‪
***@***.***‬‏>:‬

**Comment by DavidHaver** [comment]
ניסת לחפש לפי good first issue?
אני לא חלק מהפרוייקט הזה אבל אבקש ממישהו שם ליצור אתך קשר פה אם הם יכולים

![Screenshot_20240401_121324_GitHub.jpg](https://github.com/UrielOfir/os-practice/assets/152496326/93782c72-f8d7-4a65-a7fa-fb36c5e64e20)

**Comment by GityFilip** [comment]
אנסה לחפש
אני ממש לא סגורה דווקא על הפרויקט הזה
אשמח להצעה אחרת מתאימה

‫בתאריך יום ב׳, 1 באפר׳ 2024 ב-12:22 מאת ‪DavidHaver‬‏ <‪
***@***.***‬‏>:‬

**Comment by DavidHaver** [comment]
אמרו שיצרו איתך קשר
בואי תנסי להיכנס לזה ואם רואים שלא מתאים יש עוד כמה פרויקטים פעילים בjavascript

**Comment by gallaghersara** [comment]
היי גיטי, דוד הפנה את ההודעה שלך בדיסקורד, אז אם עדיין אין לך גישה את יכולה לכתוב לי במייל sgalhar@gmail.com ואנסה לעזור:)
