### ISSUE TITLE
Auto-assign

### ISSUE THREAD

**Issue by donno2048** [UrielOfir/os-practice#85]
You could make an issue template for the md creation issue and give it a special tag, then create a GitHub action that every time an issue is created if it has that tag it'll assign the issuer to the issue

**Comment by UrielOfir** [comment]
Go on it!

**Comment by UrielOfir** [comment]
I sent you e-mail. did you see it?
Can you contact me?

**Comment by donno2048** [comment]
Don't have the time to do it currently by I might do it next week if no one else wants to...

**Comment by donno2048** [comment]
> I sent you e-mail. did you see it? Can you contact me?

Sure!

**Comment by UrielOfir** [comment]
Be in touch :)

**Comment by donno2048** [comment]
I have time to do it now, I'll start working on it, however I need you to create a new label, let's say "md" for the md files creation

**Comment by donno2048** [comment]
@UrielOfir for it to work you need to create a new label named "md"

**Comment by donno2048** [comment]
Also you wrote "בחרות" istead of "בחרו"
