### ISSUE TITLE
Site Fix & Addition of Personal MD File in docs/people

### ISSUE THREAD

**Issue by DvirMon** [UrielOfir/os-practice#90]
First attempt in open source

**Comment by UrielOfir** [comment]
You wrote 'site fix'. What do you mean?

**Comment by DvirMon** [comment]
just translation for the issue guide:

תבקשו לתקן את האתר ולהוסיף קובץ md עם פרטים עליכם בתוך תיקיית docs/people . לפני המעבר לשלב הבא יש להמתין עד שהמיינטייר של הפרוייקט יגדיר אתכם assign.

**Comment by UrielOfir** [comment]
סבבה.

**Comment by DvirMon** [comment]
אז. איך ממשיכים מכאן? @UrielOfir

**Comment by UrielOfir** [comment]
כתבתי לך הערה לפול-ריקווסט:
https://github.com/UrielOfir/os-practice/pull/91#issuecomment-1675821805
