### ISSUE TITLE
בדיקה

### ISSUE THREAD

**Issue by urielwix** [UrielOfir/os-practice#98]
### Explain what you want do to (i.e. create an MD file)

להוסיף קובץ

**Comment by donno2048** [comment]
I explained in #85 that you have to create the "md" label for it to work

**Comment by donno2048** [comment]
@UrielOfir Go to https://github.com/UrielOfir/os-practice/labels and click on "New label" then give it the name "md"

**Comment by UrielOfir** [comment]
I'll send invitation to be maintainer
